# Generated by Django 5.0.3 on 2024-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Lastname')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('phone_number', models.BigIntegerField(verbose_name='Phone Number')),
                ('job', models.CharField(max_length=100, verbose_name='Job')),
                ('studies', models.CharField(max_length=50, verbose_name='Studies')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('date_added', models.DateField(auto_now=True, verbose_name='Date Added')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
